AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://s3-pei-lambda-dec7ddd4a90b8638/ce80cb3404010e286b012e3de813e9a0
      Handler: com.aws.lambda.TestLambda::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Role: arn:aws:iam::494526681395:role/pei-lambda-role
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
